import type { DashboardSpec } from "../types";
import { count, distinct, is, share, sum } from "./helpers";

export const correspondenciaSalidas: DashboardSpec = {
  slug: "correspondencia-salidas",
  dataset: "salidas_generales",
  dateField: "Fecha_radicacion",
  dateLabel: "Fecha de radicación",
  filters: [
    { field: "Tramite", label: "Trámite", kind: "multi", primary: true },
    { field: "Estado", label: "Estado", kind: "multi", primary: true },
    { field: "Canal_de_envio", label: "Canal de envío", kind: "multi", primary: true },
    { field: "Anexos", label: "Con anexos", kind: "multi", primary: true },
    { field: "Copia", label: "Copia", kind: "multi" },
    { field: "Tipo_documento_destinatario", label: "Tipo de documento", kind: "multi" },
    { field: "Departamento_destinatario", label: "Departamento", kind: "multi" },
    { field: "Municipio_destinatario", label: "Municipio", kind: "multi" },
    { field: "Aprobador", label: "Aprobador", kind: "multi" },
    { field: "Estado_guia", label: "Estado guía", kind: "multi" },
    { field: "Medio_de_envio", label: "Medio de envío", kind: "multi" },
    { field: "Tiene_correo_destinatario", label: "Correo destinatario", kind: "multi" },
    { field: "ID_envio_sealmail", label: "ID envío SealMail", kind: "text" },
    { field: "Numero_radicado", label: "Radicado", kind: "text" },
  ],
  kpis: [
    { id: "total", label: "Total salidas", measure: count(), format: "int", polarity: "neutral", hero: true, hint: "Registros de salida (incluye copias) en el periodo." },
    { id: "unicos", label: "Radicados únicos", measure: distinct("Numero_radicado"), format: "int", polarity: "neutral", hint: "Números de radicado de salida distintos." },
    { id: "aprobado", label: "% Aprobado", measure: share(is("Estado", "Aprobado")), format: "pct", polarity: "up-good", hint: "Salidas en estado Aprobado sobre el total." },
    { id: "enviado", label: "% Enviado", measure: share(is("Estado", "Enviado")), format: "pct", polarity: "neutral", hint: "Salidas en estado Enviado sobre el total." },
    { id: "digital", label: "% Canal digital", measure: share(is("Canal_de_envio", "Digital (Correo)", "Certificado (SealMail)")), format: "pct", polarity: "up-good", hint: "Salidas por correo electrónico simple o certificado (SealMail)." },
    { id: "sealmail", label: "% Envíos SealMail", measure: share(is("Canal_de_envio", "Certificado (SealMail)")), format: "pct", polarity: "neutral", hint: "Salidas enviadas por correo certificado SealMail." },
    { id: "con-correo", label: "% Con correo destinatario", measure: share(is("Tiene_correo_destinatario", "Sí")), format: "pct", polarity: "up-good", hint: "Salidas cuyo destinatario tiene correo electrónico registrado." },
    { id: "municipios", label: "Municipios cubiertos", measure: distinct("__mpio"), format: "int", polarity: "neutral", hint: "Municipios distintos de destino (código DANE)." },
    { id: "folios", label: "Cantidad de folios", measure: sum("Cantidad_de_folios", { field: "Cantidad_de_folios", lt: 9999 }), format: "int", polarity: "neutral", hint: "Suma de folios. Se excluyen valores atípicos (≥ 9.999) que llegan como relleno desde la fuente." },
    { id: "devoluciones", label: "Devoluciones", measure: count(is("Estado_guia", "DEVUELTO")), format: "int", polarity: "up-bad", provisional: true, hint: "Salidas con estado de guía DEVUELTO. Fórmula provisional." },
  ],
  sections: [
    {
      id: "tendencia",
      title: "Tendencia",
      widgets: [
        { id: "serie", type: "timeseries", title: "Salidas en el tiempo", subtitle: "La línea tenue es el periodo anterior", size: "lg", compare: true },
        { id: "tramite", type: "donut", title: "Tipo de trámite", dimension: "Tramite", size: "sm" },
        {
          id: "sealmail",
          type: "timeseries",
          title: "Envíos SealMail en el tiempo",
          series: [{ id: "sealmail", label: "Envíos SealMail", measure: count(is("Canal_de_envio", "Certificado (SealMail)")) }],
          compare: true,
          size: "lg",
        },
        { id: "canal", type: "donut", title: "Canal de envío", dimension: "Canal_de_envio", size: "sm" },
      ],
    },
    {
      id: "gestion",
      title: "Estados, aprobadores y territorio",
      widgets: [
        { id: "estado", type: "bar", orientation: "horizontal", title: "Estado", dimension: "Estado", size: "sm" },
        { id: "anexos", type: "donut", title: "Anexos", dimension: "Anexos", size: "sm" },
        { id: "aprobadores", type: "bar", orientation: "horizontal", title: "Radicados según aprobador", subtitle: "Top 10", dimension: "Aprobador", topN: 10, size: "sm", height: 360 },
        { id: "mapa", type: "map", title: "Ubicación de los destinatarios", subtitle: "Doble clic en un departamento para ver sus municipios", geoLabel: "destinatario", breakdown: { field: "Tramite", label: "Trámite" }, size: "full", height: 480 },
      ],
    },
  ],
  table: {
    title: "Detalle de correspondencia de salida",
    columns: [
      { field: "Numero_radicado", label: "Radicado salida", format: "mono" },
      { field: "Radicado_entrada", label: "Radicado entrada", format: "mono", visible: false },
      { field: "Asunto", label: "Asunto" },
      { field: "Fecha_radicacion", label: "Radicado el", format: "datetime" },
      { field: "Tramite", label: "Trámite" },
      { field: "Estado", label: "Estado", format: "badge" },
      { field: "Aprobador", label: "Aprobador" },
      { field: "Destinatario", label: "Destinatario" },
      { field: "Departamento_destinatario", label: "Departamento" },
      { field: "Municipio_destinatario", label: "Municipio" },
      { field: "ID_envio_sealmail", label: "ID SealMail", format: "mono", visible: false },
      { field: "Cantidad_de_folios", label: "Folios", format: "int", visible: false },
      { field: "Anexos", label: "Anexos", visible: false },
      { field: "Tiene_correo_destinatario", label: "Correo destinatario", visible: false },
    ],
    searchFields: ["Numero_radicado", "Radicado_entrada", "Aprobador", "Destinatario"],
    defaultSort: { field: "Fecha_radicacion", dir: "desc" },
  },
};
