import type { DashboardSpec } from "../types";
import { count, distinct, is, share, sum } from "./helpers";

/** Tableros relacionados por trámite (enlace "Ver tablero ↗" en CategoryTiles). */
const TRAMITE_LINKS: Record<string, string> = {
  PQRD: "pqrd",
  "Medicina Laboral": "medicina-laboral-salidas",
  Tutela: "tutelas",
  "Entes de control": "entes-control",
};

export const correspondenciaSalidas: DashboardSpec = {
  slug: "correspondencia-salidas",
  dataset: "salidas_generales",
  dateField: "Fecha_radicacion",
  dateLabel: "Fecha de radicación",
  unit: { singular: "salida", plural: "salidas" },
  filters: [
    { field: "Tramite", label: "Trámite", kind: "multi", primary: true },
    { field: "Estado", label: "Estado", kind: "multi", primary: true },
    { field: "Canal_de_envio", label: "Canal de envío", kind: "multi", primary: true },
    { field: "Anexos", label: "Con anexos", kind: "multi", primary: true },
    { field: "Copia", label: "Copia", kind: "multi" },
    { field: "Tipo_documento_destinatario", label: "Tipo de documento", kind: "multi" },
    { field: "Departamento_destinatario", label: "Departamento", kind: "multi" },
    { field: "Municipio_destinatario", label: "Municipio", kind: "multi" },
    { field: "Aprobador", label: "Aprobador", kind: "multi" },
    { field: "Estado_guia", label: "Estado guía", kind: "multi" },
    { field: "Medio_de_envio", label: "Medio de envío", kind: "multi" },
    { field: "Tiene_correo_destinatario", label: "Correo destinatario", kind: "multi" },
    { field: "ID_envio_sealmail", label: "ID envío SealMail", kind: "text" },
    { field: "Numero_radicado", label: "Radicado", kind: "text" },
  ],
  kpis: [
    { id: "total", label: "Total salidas", short: "Salidas", measure: count(), format: "int", polarity: "neutral", hero: true, hint: "Registros de salida (incluye copias) en el periodo." },
    { id: "unicos", label: "Radicados únicos", short: "Radicados únicos", measure: distinct("Numero_radicado"), format: "int", polarity: "neutral", hint: "Números de radicado de salida distintos." },
    { id: "aprobado", label: "% Aprobado", short: "% Aprobado", measure: share(is("Estado", "Aprobado")), format: "pct", polarity: "up-good", hint: "Salidas en estado Aprobado sobre el total." },
    { id: "enviado", label: "% Enviado", short: "% Enviado", measure: share(is("Estado", "Enviado")), format: "pct", polarity: "neutral", hint: "Salidas en estado Enviado sobre el total." },
    { id: "digital", label: "% Canal digital", short: "% Canal digital", measure: share(is("Canal_de_envio", "Digital (Correo)", "Certificado (SealMail)")), format: "pct", polarity: "up-good", hint: "Correo simple + SealMail (correo certificado) sobre el total de salidas." },
    { id: "sealmail", label: "% Envíos SealMail", short: "% SealMail", measure: share(is("Canal_de_envio", "Certificado (SealMail)")), format: "pct", polarity: "neutral", hint: "Salidas enviadas por correo certificado SealMail." },
    { id: "con-correo", label: "% Con correo destinatario", short: "% Con correo", measure: share(is("Tiene_correo_destinatario", "Sí")), format: "pct", polarity: "up-good", hint: "Salidas cuyo destinatario tiene correo electrónico registrado." },
    { id: "municipios", label: "Municipios cubiertos", short: "Municipios", measure: distinct("__mpio"), format: "int", polarity: "neutral", hint: "Municipios distintos de destino (código DANE)." },
    { id: "folios", label: "Cantidad de folios", short: "Folios", measure: sum("Cantidad_de_folios", { field: "Cantidad_de_folios", lt: 9999 }), format: "int", polarity: "neutral", hint: "Suma de folios. Se excluyen valores atípicos (≥ 9.999) que llegan como relleno desde la fuente." },
    { id: "devoluciones", label: "Devoluciones", short: "Devoluciones", measure: count(is("Estado_guia", "DEVUELTO")), format: "int", polarity: "up-bad", provisional: true, hint: "Salidas con estado de guía DEVUELTO. Fórmula provisional." },
  ],
  // kpiRedesign §6: fila 1 4-8 (igual que Entradas) · fila 2 6-6 compacta (Canal | Cobertura)
  kpiLayout: [
    {
      template: "4-8",
      cells: [
        { kind: "hero", kpi: "total" },
        { kind: "group", title: "Estado", variant: "list", kpis: ["aprobado", "enviado", "devoluciones"] },
      ],
    },
    {
      template: "6-6",
      compact: true,
      cells: [
        { kind: "group", title: "Canal", variant: "list", kpis: ["digital", "sealmail", "con-correo"] },
        { kind: "group", title: "Cobertura", variant: "list", kpis: ["unicos", "municipios", "folios"] },
      ],
    },
  ],
  sections: [
    {
      id: "destino",
      nav: "Destino",
      question: "¿A dónde van las salidas?",
      widgets: [
        {
          id: "mapa",
          type: "map",
          title: "Territorio del destinatario",
          subtitle: "Departamento y municipio · por trámite",
          geoLabel: "destinatario",
          breakdown: { field: "Tramite", label: "Trámite" },
          size: "full",
          viz: "hero-map",
          hero: true,
          vizOptions: { mapContext: "La cifra de municipios cubiertos está en el grupo Cobertura de los indicadores." },
        },
      ],
      rows: [{ template: "12", tier: "XL", cells: ["mapa"] }],
    },
    {
      id: "salidas",
      nav: "Salidas y trámite",
      question: "¿Cuánto salió y de qué tipo?",
      widgets: [
        {
          id: "serie",
          type: "timeseries",
          title: "Salidas en el tiempo",
          subtitle: "Frente al periodo anterior",
          size: "lg",
          compare: true,
          viz: "area",
          vizOptions: { mode: "auto" },
        },
        {
          id: "tramite",
          type: "bar",
          orientation: "vertical",
          title: "Tipo de trámite",
          subtitle: "Participación de cada trámite",
          dimension: "Tramite",
          size: "sm",
          viz: "category-tiles",
          vizOptions: { links: TRAMITE_LINKS },
          maxItems: 7,
        },
      ],
      rows: [{ template: "7-5", tier: "M", cells: ["serie", "tramite"] }],
    },
    {
      id: "canal",
      nav: "Canal y SealMail",
      question: "¿Qué tan digital es el envío?",
      widgets: [
        {
          id: "canal",
          type: "bar",
          orientation: "vertical",
          title: "Canal de envío",
          subtitle: "Correo simple, SealMail y sin canal",
          dimension: "Canal_de_envio",
          size: "sm",
          viz: "composition",
          // Las dos partes digitales suman el KPI "% Canal digital": "Digital (Correo)" se rotula como
          // correo simple para que no se lea como el total digital.
          vizOptions: { layout: "split", overrides: { "Digital (Correo)": { label: "Correo simple" }, "Certificado (SealMail)": { label: "SealMail" } } },
          semantic: "canal-envio",
          maxItems: 3,
        },
        {
          id: "sealmail",
          type: "timeseries",
          title: "Envíos SealMail",
          subtitle: "Correo certificado",
          series: [{ id: "sealmail", label: "Envíos SealMail", measure: count(is("Canal_de_envio", "Certificado (SealMail)")) }],
          compare: true,
          size: "lg",
          viz: "area",
          vizOptions: { mode: "auto", colorSlot: 2 },
        },
      ],
      rows: [{ template: "4-8", tier: "M", cells: ["canal", "sealmail"] }],
    },
    {
      id: "gestion",
      nav: "Estado y aprobadores",
      question: "¿En qué estado están y quién las aprueba?",
      widgets: [
        {
          id: "estado",
          type: "bar",
          orientation: "horizontal",
          title: "Estado",
          subtitle: "Ciclo de vida de la salida",
          dimension: "Estado",
          size: "sm",
          viz: "composition",
          vizOptions: { layout: "legend" },
          semantic: "flujo",
          maxItems: 6,
        },
        {
          id: "anexos",
          type: "bar",
          orientation: "vertical",
          title: "Anexos",
          subtitle: "Salidas con y sin anexos",
          dimension: "Anexos",
          size: "sm",
          viz: "composition",
          vizOptions: { layout: "split", overrides: { SI: { label: "Con anexos" }, NO: { label: "Sin anexos" } } },
          semantic: "binario",
          maxItems: 3,
        },
        {
          id: "aprobadores",
          type: "bar",
          orientation: "horizontal",
          title: "Aprobadores",
          subtitle: "Salidas aprobadas",
          dimension: "Aprobador",
          topN: 10,
          size: "full",
          viz: "people",
          vizOptions: { columns: 2 },
          labelKind: "persona",
          maxItems: 10,
        },
      ],
      rows: [
        { template: "6-6", tier: "S", cells: ["estado", "anexos"] },
        { template: "12", tier: "M", cells: ["aprobadores"] },
      ],
    },
  ],
  table: {
    title: "Detalle de correspondencia de salida",
    columns: [
      { field: "Numero_radicado", label: "Radicado salida", format: "mono" },
      { field: "Radicado_entrada", label: "Radicado entrada", format: "mono", visible: false },
      { field: "Asunto", label: "Asunto" },
      { field: "Fecha_radicacion", label: "Radicado el", format: "datetime" },
      { field: "Tramite", label: "Trámite" },
      { field: "Estado", label: "Estado", format: "badge", semantic: "flujo" },
      { field: "Aprobador", label: "Aprobador", labelKind: "persona" },
      { field: "Destinatario", label: "Destinatario" },
      { field: "Departamento_destinatario", label: "Departamento" },
      { field: "Municipio_destinatario", label: "Municipio" },
      { field: "ID_envio_sealmail", label: "ID SealMail", format: "mono", visible: false },
      { field: "Cantidad_de_folios", label: "Folios", format: "int", visible: false },
      { field: "Anexos", label: "Anexos", visible: false, semantic: "binario" },
      { field: "Tiene_correo_destinatario", label: "Correo destinatario", visible: false, semantic: "binario" },
    ],
    searchFields: ["Numero_radicado", "Radicado_entrada", "Aprobador", "Destinatario"],
    defaultSort: { field: "Fecha_radicacion", dir: "desc" },
  },
};
