import type { DashboardSpec } from "../types";
import { avg, count, distinct, sum, DIAS_ORDER } from "./helpers";

export const facturasRecibidas: DashboardSpec = {
  slug: "facturas-recibidas",
  dataset: "facturas_recibidas",
  dateField: "fecha",
  dateLabel: "Fecha de la factura",
  unit: { singular: "factura", plural: "facturas" },
  filters: [
    { field: "Hom_ultimo_Evento", label: "Último evento RADIAN", kind: "multi", primary: true },
    { field: "proveedor_nombre", label: "Proveedor", kind: "multi", primary: true },
    { field: "proveedor", label: "NIT proveedor", kind: "text", placeholder: "Ej. 900448997" },
    { field: "Aux_Numero_Factura", label: "Número de factura", kind: "text", placeholder: "Prefijo + consecutivo" },
    { field: "cufe", label: "CUFE", kind: "text" },
    { field: "prefijo", label: "Prefijo", kind: "multi" },
    { field: "dia_semana", label: "Día de la semana", kind: "multi" },
  ],
  kpis: [
    { id: "facturas", label: "Facturas recibidas", short: "Facturas", measure: count(), format: "int", polarity: "neutral", hero: true, hint: "Número de facturas electrónicas recibidas con fecha dentro del periodo." },
    { id: "valor", label: "Valor total recibido", short: "Valor recibido", measure: sum("valor"), format: "cop", polarity: "neutral", hint: "Suma del valor de las facturas recibidas en el periodo, en pesos colombianos." },
    { id: "proveedores", label: "Proveedores activos", short: "Proveedores", measure: distinct("proveedor"), format: "int", polarity: "neutral", hint: "Proveedores distintos (NIT) con al menos una factura en el periodo." },
    { id: "ticket", label: "Valor promedio por factura", short: "Valor promedio", measure: avg("valor"), format: "cop", polarity: "neutral", hint: "Valor total recibido dividido entre el número de facturas." },
  ],
  // kpiRedesign §6: héroe + grupo "Valor y proveedores" (150 + 150 + 112 + divisores ≤ 671)
  kpiLayout: [
    {
      template: "4-8",
      cells: [
        { kind: "hero", kpi: "facturas" },
        { kind: "group", title: "Valor y proveedores", variant: "list", kpis: ["valor", "ticket", "proveedores"] },
      ],
    },
  ],
  sections: [
    {
      id: "volumen",
      nav: "Volumen",
      question: "¿Cómo llega el volumen del periodo?",
      widgets: [
        {
          id: "serie",
          type: "timeseries",
          title: "Facturas recibidas",
          subtitle: "Frente al periodo anterior",
          size: "full",
          compare: true,
          viz: "area",
          vizOptions: { mode: "auto", colorSlot: 1 },
          hero: true,
        },
        {
          id: "dias",
          type: "bar",
          orientation: "vertical",
          title: "Día de la semana",
          subtitle: "Facturas del periodo por día",
          dimension: "dia_semana",
          sort: "natural",
          order: DIAS_ORDER,
          size: "sm",
          viz: "column-bars",
          vizOptions: { preset: "semana" },
          maxItems: 7,
        },
      ],
      rows: [{ template: "8-4", tier: "L", cells: ["serie", "dias"] }],
    },
    {
      id: "anio",
      nav: "Año en curso",
      question: "¿Cómo va el año en cantidad y valor?",
      widgets: [
        { id: "mensual-cantidad", type: "monthly", title: "Facturas por mes", subtitle: "Enero a hoy · variación mensual", size: "md", scope: "ytd", colorSlot: 1, viz: "monthly-delta", vizOptions: { colorSlot: 1 } },
        { id: "mensual-valor", type: "monthly", title: "Valor por mes", subtitle: "Pesos · enero a hoy · variación mensual", size: "md", scope: "ytd", measure: sum("valor"), valueFormat: "cop", colorSlot: 2, viz: "monthly-delta", vizOptions: { colorSlot: 2 } },
      ],
      rows: [{ template: "6-6", tier: "M", cells: ["mensual-cantidad", "mensual-valor"] }],
    },
    {
      id: "radian",
      nav: "Ciclo RADIAN",
      question: "¿En qué etapa de aceptación están?",
      widgets: [
        {
          id: "eventos",
          type: "bar",
          orientation: "vertical",
          title: "Último evento RADIAN",
          subtitle: "Etapa de aceptación",
          dimension: "Hom_ultimo_Evento",
          size: "sm",
          viz: "status-strip",
          vizOptions: { variant: "vertical" },
          semantic: "radian",
          maxItems: 3,
        },
        {
          id: "eventos-serie",
          type: "timeseries",
          title: "Evolución por evento",
          subtitle: "Por último evento, apilado",
          splitBy: "Hom_ultimo_Evento",
          splitTopN: 4,
          size: "lg",
          viz: "area",
          vizOptions: { mode: "stacked", legendFrom: "eventos" },
          semantic: "radian",
        },
      ],
      rows: [{ template: "4-8", tier: "M", cells: ["eventos", "eventos-serie"] }],
    },
    {
      id: "proveedores",
      nav: "Proveedores",
      question: "¿Qué tan concentrada está la facturación?",
      widgets: [
        {
          id: "top-proveedores",
          type: "bar",
          orientation: "horizontal",
          title: "Proveedores con más facturas",
          subtitle: "Top 10 por cantidad de facturas",
          dimension: "proveedor_nombre",
          topN: 10,
          size: "lg",
          viz: "ranking",
          vizOptions: { columns: 2, concentration: true },
          labelKind: "proveedor",
          maxItems: 10,
        },
      ],
      rows: [{ template: "12", tier: "M", cells: ["top-proveedores"] }],
    },
  ],
  table: {
    title: "Detalle de facturas recibidas",
    columns: [
      { field: "id", label: "ID", format: "mono" },
      { field: "ofe", label: "OFE", format: "mono", visible: false },
      { field: "proveedor", label: "NIT proveedor", format: "mono", visible: false },
      { field: "proveedor_nombre", label: "Proveedor", labelKind: "proveedor" },
      { field: "Aux_Numero_Factura", label: "Factura", format: "mono" },
      { field: "consecutivo", label: "Consecutivo", format: "mono", visible: false },
      { field: "cufe", label: "CUFE", format: "mono", visible: false },
      { field: "dia_semana", label: "Día" },
      { field: "fecha", label: "Fecha y hora", format: "datetime" },
      { field: "Solo_hora", label: "Hora (franja)", format: "int", visible: false },
      { field: "Hom_ultimo_Evento", label: "Último evento RADIAN", format: "badge", semantic: "radian" },
      { field: "valor", label: "Valor", format: "cop" },
    ],
    searchFields: ["Aux_Numero_Factura", "cufe", "proveedor", "proveedor_nombre", "id"],
    defaultSort: { field: "fecha", dir: "desc" },
  },
};
