import type { DashboardSpec } from "../types";
import { count, distinct, is, share, sum, DIAS_ORDER } from "./helpers";

export const facturasEmitidas: DashboardSpec = {
  slug: "facturas-emitidas",
  dataset: "facturas_emitidas",
  dateField: "fecha_expedicion",
  dateLabel: "Fecha de expedición",
  unit: { singular: "factura", plural: "facturas" },
  filters: [
    { field: "estado", label: "Estado", kind: "multi", primary: true },
    { field: "tipo_documento", label: "Tipo de documento", kind: "multi", primary: true },
    { field: "adquiriente_nombre", label: "Adquiriente", kind: "multi", primary: true },
    { field: "nit_adquiriente", label: "NIT adquiriente", kind: "text" },
    { field: "AUX_Numero_Factura", label: "Número de factura", kind: "text" },
    { field: "nro_resolucion", label: "Número de resolución", kind: "multi" },
    { field: "forma_pago", label: "Forma de pago", kind: "multi" },
  ],
  kpis: [
    { id: "facturas", label: "Facturas emitidas", short: "Facturas", measure: count(), format: "int", polarity: "neutral", hero: true, hint: "Facturas expedidas en el periodo (incluye inconsistentes)." },
    { id: "valor", label: "Valor facturas emitidas", short: "Valor neto", measure: sum("valor_neto"), format: "cop", polarity: "neutral", hint: "Suma del valor neto de las facturas expedidas en el periodo." },
    { id: "adquirientes", label: "Adquirientes", short: "Adquirientes", measure: distinct("nit_adquiriente"), format: "int", polarity: "neutral", hint: "Adquirientes distintos (NIT/cédula) facturados en el periodo." },
    { id: "inconsistentes", label: "% Inconsistentes", short: "% Inconsistentes", measure: share(is("estado", "INCONSISTENTE")), format: "pct", polarity: "up-bad", hint: "Facturas en estado INCONSISTENTE sobre el total (normalmente adquiriente no encontrado para el OFE)." },
  ],
  // kpiRedesign §6: héroe + par valor · adquirientes (150 + 112 ≤ 305) + tile de estado con la TASA de inconsistentes
  kpiLayout: [
    {
      template: "4-4-4",
      cells: [
        { kind: "hero", kpi: "facturas" },
        { kind: "group", title: "Valor y adquirientes", variant: "pair", kpis: ["valor", "adquirientes"] },
        {
          kind: "tile",
          kpi: "inconsistentes",
          variant: "status",
          tone: "critical",
          action: { label: "Ver inconsistentes", filter: { field: "estado", value: "INCONSISTENTE" } },
        },
      ],
    },
  ],
  sections: [
    {
      id: "ritmo",
      nav: "Ritmo de emisión",
      question: "¿Cuándo emite la operación?",
      widgets: [
        {
          id: "dia-hora",
          type: "pivot",
          title: "Facturas por día y hora",
          rows: [{ field: "dia_semana", label: "Día" }],
          columns: { field: "Solo_Hora", label: "Hora" },
          rowOrder: DIAS_ORDER,
          stableRows: true,
          fillNumericColumns: true,
          maxRows: 7,
          size: "full",
        },
        {
          id: "dias",
          type: "bar",
          orientation: "vertical",
          title: "Facturas por día de la semana",
          subtitle: "Conteo y participación por día",
          dimension: "dia_semana",
          sort: "natural",
          order: DIAS_ORDER,
          size: "sm",
          viz: "column-bars",
          vizOptions: { preset: "semana" },
          maxItems: 7,
        },
        {
          id: "horas",
          type: "bar",
          orientation: "vertical",
          title: "Facturas por hora",
          subtitle: "Hora de expedición (0–23)",
          dimension: "Solo_Hora",
          sort: "label",
          size: "lg",
          viz: "column-bars",
          maxItems: 24,
        },
      ],
      rows: [
        {
          template: "12",
          tier: "L",
          cells: [
            {
              composite: "heatmap-matrix",
              id: "ritmo",
              widgets: ["dia-hora", "dias", "horas"],
              title: "Facturas por día y hora",
              subtitle: "Día de la semana × hora de expedición",
              hero: true,
            },
          ],
        },
      ],
    },
    {
      id: "anio",
      nav: "Año en curso",
      question: "¿Cómo va el año en cantidad y valor?",
      widgets: [
        { id: "mensual-cantidad", type: "monthly", title: "Facturas por mes", subtitle: "Enero a hoy · variación mensual", size: "md", scope: "ytd", colorSlot: 1, viz: "monthly-delta", vizOptions: { colorSlot: 1 } },
        { id: "mensual-valor", type: "monthly", title: "Valor neto por mes", subtitle: "Pesos · enero a hoy · variación mensual", size: "md", scope: "ytd", measure: sum("valor_neto"), valueFormat: "cop", colorSlot: 2, viz: "monthly-delta", vizOptions: { colorSlot: 2 } },
      ],
      rows: [{ template: "6-6", tier: "M", cells: ["mensual-cantidad", "mensual-valor"] }],
    },
    {
      id: "calidad",
      nav: "Calidad y adquirientes",
      question: "¿Qué parte es inconsistente y a quién facturamos?",
      widgets: [
        {
          id: "estado-tipo",
          type: "bartable",
          title: "Estado por tipo",
          subtitle: "Emitidas e inconsistentes",
          columns: [{ field: "estado", label: "Estado" }, { field: "tipo_documento", label: "Tipo" }],
          measureLabel: "Cantidad",
          size: "md",
          viz: "composition",
          vizOptions: { layout: "split" },
          semantic: "factura",
          maxItems: 2,
        },
        {
          id: "top-adquirientes",
          type: "bartable",
          title: "Adquirientes con más facturas",
          subtitle: "Top 60 por cantidad de facturas",
          columns: [{ field: "adquiriente_nombre", label: "Adquiriente" }],
          measureLabel: "Facturas",
          topN: 60,
          size: "md",
          viz: "ranking",
          vizOptions: { pinned: { label: "Adquiriente no encontrado", cta: "Ver inconsistentes", filter: { field: "estado", value: "INCONSISTENTE" } } },
          labelKind: "proveedor",
          maxItems: 60,
          visibleRows: 7,
        },
      ],
      rows: [{ template: "4-8", tier: "L", cells: ["estado-tipo", "top-adquirientes"] }],
    },
    {
      id: "resoluciones",
      nav: "Resoluciones DIAN",
      question: "¿Con qué resoluciones se factura?",
      widgets: [
        {
          id: "resoluciones",
          type: "bartable",
          title: "Valor neto por resolución",
          subtitle: "Vigencia, consecutivos y documento",
          columns: [
            { field: "estado", label: "Estado" },
            { field: "nro_resolucion", label: "Resolución" },
            { field: "fecha_inicio", label: "Fecha inicial" },
            { field: "fecha_fin", label: "Fecha final" },
            { field: "consecutivo_inicial", label: "Consecutivo inicial" },
            { field: "consecutivo_final", label: "Consecutivo final" },
            { field: "tipo_documento", label: "Documento" },
          ],
          measure: sum("valor_neto"),
          measureLabel: "Valor neto",
          valueFormat: "cop",
          size: "full",
          viz: "resolution-table",
          semantic: "factura",
          note: "La resolución 99999999999999 es un valor de relleno que llega desde la fuente en facturas inconsistentes.",
        },
      ],
      rows: [{ template: "12", tier: "auto", cells: ["resoluciones"] }],
    },
  ],
  table: {
    title: "Detalle de facturas emitidas",
    columns: [
      { field: "id", label: "ID", format: "mono" },
      { field: "nit_oferente", label: "Oferente", format: "mono", visible: false },
      { field: "nit_adquiriente", label: "NIT adquiriente", format: "mono" },
      { field: "adquiriente_nombre", label: "Adquiriente", labelKind: "proveedor" },
      { field: "AUX_Numero_Factura", label: "Número", format: "mono" },
      { field: "forma_pago", label: "Forma de pago", visible: false },
      { field: "medio_pago", label: "Medio de pago", visible: false },
      { field: "dia_semana", label: "Día", visible: false },
      { field: "fecha_expedicion", label: "Expedición", format: "datetime" },
      { field: "valor_neto", label: "Valor neto", format: "cop" },
      { field: "estado", label: "Estado", format: "badge", semantic: "factura" },
      { field: "mensaje", label: "Mensaje", format: "long" },
    ],
    searchFields: ["AUX_Numero_Factura", "nit_adquiriente", "adquiriente_nombre", "id"],
    defaultSort: { field: "fecha_expedicion", dir: "desc" },
  },
};
