import type { DashboardSpec } from "../types";
import { avg, count, is, share } from "./helpers";

export const medicinaLaboralEntradas: DashboardSpec = {
  slug: "medicina-laboral-entradas",
  dataset: "ml_entradas",
  dateField: "Fecha_de_radicacion",
  dateLabel: "Fecha de radicación",
  unit: { singular: "radicado", plural: "radicados" },
  filters: [
    { field: "tipo_tramite", label: "Tipo de trámite", kind: "multi", primary: true },
    { field: "estado", label: "Estado", kind: "multi", primary: true },
    { field: "oficina_solicitud", label: "Oficina", kind: "multi", primary: true },
    { field: "canal_radicacion", label: "Canal de radicación", kind: "multi", primary: true },
    { field: "prefijo", label: "Prefijo", kind: "multi" },
    { field: "subproceso", label: "Subproceso", kind: "multi" },
    { field: "medio_envio", label: "Medio de envío", kind: "multi" },
    { field: "proceso_asistente", label: "Proceso asistente", kind: "multi" },
    { field: "gestionador_responsable", label: "Gestionador", kind: "multi" },
    { field: "revisor", label: "Revisor", kind: "multi" },
    { field: "tiempo_por_vencer", label: "Tiempo por vencer", kind: "multi" },
    { field: "asignador_responsable", label: "Asignador", kind: "multi" },
    { field: "responsable_aprobacion", label: "Responsable de aprobación", kind: "multi" },
    { field: "tipo_solicitud", label: "Tipo de solicitud", kind: "multi" },
    { field: "fecha_max_respuesta", label: "Fecha máxima de respuesta", kind: "date" },
    { field: "fecha_aprobacion", label: "Fecha de aprobación", kind: "date" },
    { field: "numero_radicado", label: "Radicado", kind: "text" },
  ],
  kpis: [
    { id: "radicados", label: "Radicados", short: "Radicados", measure: count(), format: "int", polarity: "neutral", hero: true, hint: "Radicados de entrada de medicina laboral en el periodo." },
    { id: "aprobados", label: "Aprobados en el periodo", short: "Aprobados", measure: count(), dateField: "fecha_aprobacion", format: "int", polarity: "up-good", provisional: true, hint: "Radicados cuya fecha de aprobación cae dentro del periodo, sin importar cuándo se radicaron. Por eso puede superar a los radicados." },
    // La etiqueta nombra las DOS categorías que suma: con "% Vencidos" contradecía el tile "Vencido" del StatusStrip
    { id: "vencidos", label: "% Vencido o fuera de término", short: "% Fuera de plazo", measure: share(is("tiempo_por_vencer", "Vencido", "Fuera de Término")), format: "pct", polarity: "up-bad", hint: "Radicados vencidos o respondidos fuera de término sobre el total. Suma Vencido + Fuera de término del widget Tiempo por vencer." },
    { id: "tiempo-gestion", label: "Tiempo en gestión (promedio)", short: "Días en gestión", measure: avg("tiempo_en_gestion"), format: "days", polarity: "up-bad", hint: "Promedio de días en gestión (solo registros con dato)." },
  ],
  // kpiRedesign §6: héroe + Aprobados (provisional) · % Fuera de plazo · Días en gestión (3 × 112 + divisores ≤ 671)
  kpiLayout: [
    {
      template: "4-8",
      cells: [
        { kind: "hero", kpi: "radicados" },
        { kind: "group", title: "Aprobación y oportunidad", variant: "list", kpis: ["aprobados", "vencidos", "tiempo-gestion"] },
      ],
    },
  ],
  sections: [
    {
      id: "oportunidad",
      nav: "Oportunidad",
      question: "¿Respondemos a tiempo?",
      widgets: [
        {
          id: "tiempo-vencer",
          type: "bar",
          orientation: "vertical",
          title: "Tiempo por vencer",
          subtitle: "Frente a la fecha máxima de respuesta",
          dimension: "tiempo_por_vencer",
          size: "sm",
          viz: "status-strip",
          semantic: "cumplimiento",
          maxItems: 4,
        },
        {
          id: "tiempo-gestion",
          type: "histogram",
          title: "Tiempo en gestión",
          subtitle: "Radicados por días · solo con dato",
          field: "tiempo_en_gestion",
          unit: "días",
          bins: [1, 2, 3, 4, 5, 6, 7, 8, 10, 15, 30],
          size: "md",
          viz: "histogram",
          vizOptions: { referenceKpi: "tiempo-gestion" },
        },
      ],
      rows: [{ template: "5-7", tier: "M", cells: ["tiempo-vencer", "tiempo-gestion"] }],
    },
    {
      id: "territorio",
      nav: "Territorio",
      question: "¿Dónde están los destinatarios?",
      widgets: [
        {
          id: "mapa",
          type: "map",
          title: "Territorio del destinatario",
          subtitle: "Radicados · desglose por tipo de trámite",
          geoLabel: "destinatario",
          breakdown: { field: "tipo_tramite", label: "Tipo de trámite" },
          size: "full",
          viz: "hero-map",
          hero: true,
        },
      ],
      rows: [{ template: "12", tier: "XL", cells: ["mapa"] }],
    },
    {
      id: "flujo",
      nav: "Flujo de entrada",
      question: "¿Cómo entran los radicados y por dónde llegan?",
      widgets: [
        {
          id: "serie",
          type: "timeseries",
          title: "Radicados y aprobados",
          subtitle: "Por radicación y aprobación",
          series: [
            { id: "radicados", label: "Radicados" },
            { id: "aprobados", label: "Radicados aprobados", dateField: "fecha_aprobacion" },
          ],
          size: "full",
          viz: "area",
          vizOptions: { mode: "lines" },
        },
        {
          id: "tipo-tramite",
          type: "bar",
          orientation: "vertical",
          title: "Tipo de trámite",
          subtitle: "Participación de cada trámite",
          dimension: "tipo_tramite",
          size: "sm",
          viz: "composition",
          vizOptions: { layout: "split" },
          maxItems: 2,
        },
        {
          id: "canal",
          type: "bar",
          orientation: "vertical",
          title: "Canal de radicación",
          subtitle: "Por dónde llegan los radicados",
          dimension: "canal_radicacion",
          // Mismo color por canal que en PQRD, Entes y Tutelas (Mail naranja, Web azul, Ventanilla aqua, Mail IA
          // amarillo). ML no tiene "Email" aparte de "Mail", así que la familia no junta dos canales en un color.
          semantic: "canal-radicacion",
          size: "md",
          viz: "composition",
          vizOptions: { layout: "legend" },
          maxItems: 5,
        },
        {
          id: "oficinas",
          type: "bar",
          orientation: "horizontal",
          title: "Oficinas asignadas",
          subtitle: "Radicados por oficina",
          dimension: "oficina_solicitud",
          size: "md",
          viz: "composition",
          vizOptions: { layout: "legend" },
          labelKind: "oficina",
          maxItems: 6,
        },
      ],
      rows: [
        { template: "8-4", tier: "M", cells: ["serie", "tipo-tramite"] },
        // 6-6 S (doc): las dos leyendas quedan en 2 columnas con la misma densidad (50 + 3 × 24 = 122 ≤ 184)
        { template: "6-6", tier: "S", cells: ["canal", "oficinas"] },
      ],
    },
    {
      id: "solicitudes",
      nav: "Solicitudes y estados",
      question: "¿Qué se solicita y en qué estado está?",
      widgets: [
        {
          id: "tipo-solicitud",
          type: "bar",
          orientation: "horizontal",
          title: "Tipo de solicitud",
          subtitle: "Radicados por tipo de solicitud",
          dimension: "tipo_solicitud",
          size: "md",
          viz: "ranking",
          maxItems: 8,
        },
        {
          id: "estados",
          type: "bar",
          orientation: "horizontal",
          title: "Estados de radicación",
          subtitle: "Estado actual por etapa del flujo",
          dimension: "estado",
          size: "md",
          viz: "status-board",
          semantic: "flujo",
          maxItems: 15,
        },
      ],
      rows: [{ template: "6-6", tier: "L", cells: ["tipo-solicitud", "estados"] }],
    },
    {
      id: "responsables",
      nav: "Responsables",
      question: "¿Quién gestiona y revisa los radicados?",
      widgets: [
        {
          id: "gestionadores",
          type: "bar",
          orientation: "horizontal",
          title: "Gestionadores",
          dimension: "gestionador_responsable",
          topN: 10,
          size: "md",
          viz: "people",
          vizOptions: { compact: true },
          labelKind: "persona",
          maxItems: 10,
        },
        {
          id: "revisores",
          type: "bar",
          orientation: "horizontal",
          title: "Revisores",
          dimension: "revisor",
          topN: 10,
          size: "md",
          viz: "people",
          vizOptions: { compact: true },
          labelKind: "persona",
          maxItems: 10,
        },
      ],
      rows: [{ template: "6-6", tier: "L", cells: ["gestionadores", "revisores"] }],
    },
  ],
  table: {
    title: "Detalle de entradas de medicina laboral",
    columns: [
      { field: "numero_radicado", label: "Radicado", format: "mono" },
      { field: "gestionador_responsable", label: "Gestionador", labelKind: "persona" },
      { field: "estado", label: "Estado", format: "badge", semantic: "flujo" },
      { field: "fecha_max_respuesta", label: "Fecha máxima", format: "date" },
      { field: "tiempo_por_vencer", label: "Tiempo por vencer", format: "badge", semantic: "cumplimiento" },
      { field: "Fecha_de_radicacion", label: "Radicado el", format: "datetime" },
      { field: "canal_radicacion", label: "Canal", semantic: "canal-radicacion" },
      { field: "oficina_solicitud", label: "Oficina", labelKind: "oficina" },
      { field: "proceso_asistente", label: "Proceso asistente", visible: false },
      { field: "subproceso", label: "Subproceso", visible: false },
      { field: "tipo_solicitud", label: "Tipo de solicitud", visible: false },
      { field: "tiempo_en_gestion", label: "Tiempo en gestión (días)", format: "int", visible: false },
      { field: "responsable_aprobacion", label: "Aprobador", labelKind: "persona", visible: false },
      { field: "revisor", label: "Revisor", labelKind: "persona", visible: false },
      { field: "radicado_salida", label: "Radicado de salida", format: "mono", visible: false },
      { field: "medio_envio", label: "Medio de envío", visible: false },
      { field: "estado_salida", label: "Estado de salida", visible: false },
      { field: "con_copia", label: "Con copia", visible: false },
    ],
    searchFields: ["numero_radicado", "gestionador_responsable", "revisor", "radicado_salida"],
    defaultSort: { field: "Fecha_de_radicacion", dir: "desc" },
  },
};
