import type { DashboardSpec } from "../types";
import { avg, count, is, share } from "./helpers";

export const medicinaLaboralEntradas: DashboardSpec = {
  slug: "medicina-laboral-entradas",
  dataset: "ml_entradas",
  dateField: "Fecha_de_radicacion",
  dateLabel: "Fecha de radicación",
  filters: [
    { field: "tipo_tramite", label: "Tipo de trámite", kind: "multi", primary: true },
    { field: "estado", label: "Estado", kind: "multi", primary: true },
    { field: "oficina_solicitud", label: "Oficina", kind: "multi", primary: true },
    { field: "canal_radicacion", label: "Canal de radicación", kind: "multi", primary: true },
    { field: "prefijo", label: "Prefijo", kind: "multi" },
    { field: "subproceso", label: "Subproceso", kind: "multi" },
    { field: "medio_envio", label: "Medio de envío", kind: "multi" },
    { field: "proceso_asistente", label: "Proceso asistente", kind: "multi" },
    { field: "gestionador_responsable", label: "Gestionador", kind: "multi" },
    { field: "revisor", label: "Revisor", kind: "multi" },
    { field: "tiempo_por_vencer", label: "Tiempo por vencer", kind: "multi" },
    { field: "asignador_responsable", label: "Asignador", kind: "multi" },
    { field: "responsable_aprobacion", label: "Responsable de aprobación", kind: "multi" },
    { field: "tipo_solicitud", label: "Tipo de solicitud", kind: "multi" },
    { field: "fecha_max_respuesta", label: "Fecha máxima de respuesta", kind: "date" },
    { field: "fecha_aprobacion", label: "Fecha de aprobación", kind: "date" },
    { field: "numero_radicado", label: "Radicado", kind: "text" },
  ],
  kpis: [
    { id: "radicados", label: "Radicados", measure: count(), format: "int", polarity: "neutral", hero: true, hint: "Radicados de entrada de medicina laboral en el periodo." },
    { id: "aprobados", label: "Aprobados en el periodo", measure: count(), dateField: "fecha_aprobacion", format: "int", polarity: "up-good", provisional: true, hint: "Radicados cuya fecha de aprobación cae dentro del periodo, sin importar cuándo se radicaron. Por eso puede superar a los radicados." },
    { id: "vencidos", label: "% Vencidos / fuera de término", measure: share(is("tiempo_por_vencer", "Vencido", "Fuera de Término")), format: "pct", polarity: "up-bad", hint: "Radicados vencidos o respondidos fuera de término sobre el total." },
    { id: "tiempo-gestion", label: "Tiempo en gestión (promedio)", measure: avg("tiempo_en_gestion"), format: "days", polarity: "up-bad", hint: "Promedio de días en gestión (solo registros con dato)." },
  ],
  sections: [
    {
      id: "responsables",
      title: "Responsables",
      widgets: [
        { id: "gestionadores", type: "bar", orientation: "horizontal", title: "Gestionador responsable", subtitle: "Top 10", dimension: "gestionador_responsable", topN: 10, size: "md" },
        { id: "revisores", type: "bar", orientation: "horizontal", title: "Revisor responsable", subtitle: "Top 10", dimension: "revisor", topN: 10, size: "md" },
      ],
    },
    {
      id: "tiempos",
      title: "Tiempos y estados",
      widgets: [
        { id: "tiempo-vencer", type: "donut", title: "Tiempo por vencer", dimension: "tiempo_por_vencer", size: "sm" },
        { id: "tiempo-gestion", type: "histogram", title: "Tiempo en gestión", subtitle: "Distribución de días en gestión", field: "tiempo_en_gestion", unit: "días", bins: [1, 2, 3, 4, 5, 6, 7, 8, 10, 15, 30], size: "md" },
        { id: "tipo-tramite", type: "bar", orientation: "vertical", title: "Tipo de trámite", dimension: "tipo_tramite", size: "sm" },
        { id: "estados", type: "bar", orientation: "horizontal", title: "Estados de radicación", dimension: "estado", topN: 12, others: true, size: "md" },
        { id: "canal", type: "bar", orientation: "vertical", title: "Canal de radicación", dimension: "canal_radicacion", size: "md" },
      ],
    },
    {
      id: "oficinas",
      title: "Oficinas y solicitudes",
      widgets: [
        { id: "oficinas", type: "bar", orientation: "horizontal", title: "Oficinas asignadas", dimension: "oficina_solicitud", size: "md" },
        { id: "tipo-solicitud", type: "bar", orientation: "horizontal", title: "Tipo de solicitud", dimension: "tipo_solicitud", size: "md" },
        {
          id: "serie",
          type: "timeseries",
          title: "Radicados y aprobados a lo largo del tiempo",
          subtitle: "Radicados por fecha de radicación · aprobados por fecha de aprobación",
          series: [
            { id: "radicados", label: "Radicados" },
            { id: "aprobados", label: "Radicados aprobados", dateField: "fecha_aprobacion" },
          ],
          size: "full",
        },
        { id: "mapa", type: "map", title: "Destinatarios por territorio", subtitle: "Doble clic en un departamento para ver sus municipios", geoLabel: "destinatario", breakdown: { field: "tipo_tramite", label: "Tipo de trámite" }, size: "full", height: 460 },
      ],
    },
  ],
  table: {
    title: "Detalle de entradas de medicina laboral",
    columns: [
      { field: "numero_radicado", label: "Radicado", format: "mono" },
      { field: "gestionador_responsable", label: "Gestionador" },
      { field: "estado", label: "Estado", format: "badge" },
      { field: "fecha_max_respuesta", label: "Fecha máxima", format: "date" },
      { field: "tiempo_por_vencer", label: "Tiempo por vencer" },
      { field: "Fecha_de_radicacion", label: "Radicado el", format: "datetime" },
      { field: "canal_radicacion", label: "Canal" },
      { field: "oficina_solicitud", label: "Oficina" },
      { field: "proceso_asistente", label: "Proceso asistente", visible: false },
      { field: "subproceso", label: "Subproceso", visible: false },
      { field: "tipo_solicitud", label: "Tipo de solicitud", visible: false },
      { field: "tiempo_en_gestion", label: "Tiempo en gestión (días)", format: "int", visible: false },
      { field: "responsable_aprobacion", label: "Aprobador", visible: false },
      { field: "revisor", label: "Revisor", visible: false },
      { field: "radicado_salida", label: "Radicado de salida", format: "mono", visible: false },
      { field: "medio_envio", label: "Medio de envío", visible: false },
      { field: "estado_salida", label: "Estado de salida", visible: false },
      { field: "con_copia", label: "Con copia", visible: false },
    ],
    searchFields: ["numero_radicado", "gestionador_responsable", "revisor", "radicado_salida"],
    defaultSort: { field: "Fecha_de_radicacion", dir: "desc" },
  },
};
