import type { DashboardSpec } from "../types";
import { SEMAFORO_GROUPS } from "./entes-common";
import { avg, count, is, share, SEMAFORO_ORDER, SEMAFORO_TILE_LABELS } from "./helpers";

/** Flujo de respuesta de la PQRD (orden de proceso para PipelineSteps). */
const ESTADOS_ORDER = ["Por asignar", "Para gestión", "En edición", "Por aprobar", "Aprobado"];

export const pqrd: DashboardSpec = {
  slug: "pqrd",
  dataset: "pqrd",
  dateField: "fecha_de_radicado",
  dateLabel: "Fecha de radicado",
  unit: { singular: "radicado", plural: "radicados" },
  filters: [
    { field: "estado", label: "Estado", kind: "multi", primary: true },
    { field: "canal_de_radicacion", label: "Canal", kind: "multi", primary: true },
    { field: "oficina_responsable_de_respuesta", label: "Oficina responsable", kind: "multi", primary: true },
    { field: "tipologia_de_pqrd", label: "Tipología", kind: "multi", primary: true },
    { field: "tiempo_por_vencer", label: "Tiempos por vencer", kind: "multi" },
    { field: "nombre_tipo_solicitud", label: "Tipo de solicitud", kind: "multi" },
    { field: "semaforo_riesgo", label: "Semáforo de riesgo", kind: "multi" },
    { field: "rango_ciclo", label: "Rango ciclo en días", kind: "multi" },
    { field: "producto", label: "Producto", kind: "multi" },
    { field: "gestionador_responsable", label: "Gestionador", kind: "multi" },
    { field: "resultado_favorabilidad", label: "Favorabilidad", kind: "multi" },
    { field: "numero_de_radicado", label: "Número de radicado", kind: "text" },
  ],
  kpis: [
    { id: "radicados", label: "Radicados", short: "Radicados", measure: count(), format: "int", polarity: "neutral", hero: true, hint: "PQRD radicadas en el periodo." },
    { id: "asignacion", label: "Asignación (promedio días)", short: "Asignación", measure: avg("num_dias_asignacion_gestionador"), format: "days", polarity: "up-bad", hint: "Promedio de días entre la asignación a la oficina y la asignación al gestionador." },
    { id: "aprobacion", label: "Aprobación (promedio días)", short: "Aprobación", measure: avg("num_dias_aprobacion"), format: "days", polarity: "up-bad", hint: "Promedio de días que toma la aprobación de la respuesta." },
    { id: "sla", label: "% Cumplimiento SLA", short: "% SLA", measure: share(is("cumplimiento_sla", "En Término")), format: "pct", polarity: "up-good", hint: "Radicados con cumplimiento de SLA “En Término” sobre el total del periodo." },
    { id: "gestion", label: "Gestión (promedio días)", short: "Gestión", measure: avg("num_dias_gestion_total"), format: "days", polarity: "up-bad", hint: "Promedio de días totales de gestión del gestionador." },
    { id: "ciclo", label: "Ciclo total (promedio días)", short: "Ciclo total", measure: avg("dias_ciclo_total"), format: "days", polarity: "up-bad", hint: "Promedio de días calendario entre radicación y cierre (solo casos cerrados)." },
  ],
  // kpiRedesign §6: 3-3-6 · [héroe radicados] [gauge SLA] [stepper de fases | Ciclo total]
  kpiLayout: [
    {
      template: "3-3-6",
      cells: [
        { kind: "hero", kpi: "radicados" },
        { kind: "tile", kpi: "sla", variant: "gauge" },
        { kind: "group", title: "Días promedio por fase", variant: "stepper", kpis: ["asignacion", "gestion", "aprobacion"], after: ["ciclo"] },
      ],
    },
  ],
  sections: [
    {
      id: "cumplimiento",
      nav: "Cumplimiento",
      question: "¿Respondemos a tiempo y dónde se acumulan los casos?",
      widgets: [
        {
          id: "semaforo",
          type: "bar",
          orientation: "horizontal",
          title: "Semáforo de riesgo",
          subtitle: "Abiertos y cerrados por nivel de riesgo",
          dimension: "semaforo_riesgo",
          sort: "natural",
          order: SEMAFORO_ORDER,
          size: "sm",
          viz: "status-strip",
          vizOptions: { variant: "horizontal", groups: SEMAFORO_GROUPS, overrides: SEMAFORO_TILE_LABELS },
          semantic: "semaforo",
          maxItems: 6,
        },
        {
          id: "estados",
          type: "bar",
          orientation: "horizontal",
          title: "Estado del flujo",
          subtitle: "Radicados por etapa del flujo de respuesta",
          dimension: "estado",
          sort: "natural",
          order: ESTADOS_ORDER,
          size: "sm",
          viz: "pipeline",
          vizOptions: { finalStage: "Aprobado" },
          semantic: "flujo",
          maxItems: 5,
        },
      ],
      // 7-5 M (igual que Entes): el semáforo agrupado cabe en 2 líneas (24 + 2 × (28 + 76) + 8 = 240 ≤ 284) y el
      // pipeline pasa a vertical en 397 px (24 + 5 × 48 = 264 ≤ 284). Evita dos filas S con la mitad vacía.
      rows: [{ template: "7-5", tier: "M", cells: ["semaforo", "estados"] }],
    },
    {
      id: "territorio",
      nav: "Territorio",
      question: "¿De dónde vienen los radicados?",
      widgets: [
        {
          id: "mapa",
          type: "map",
          title: "Radicados por territorio",
          subtitle: "Remitente · desglose por canal",
          geoLabel: "remitente",
          breakdown: { field: "canal_de_radicacion", label: "Canal" },
          size: "full",
          viz: "hero-map",
          hero: true,
        },
      ],
      rows: [{ template: "12", tier: "XL", cells: ["mapa"] }],
    },
    {
      id: "entrada",
      nav: "Tendencia",
      question: "¿Cómo evoluciona y por dónde llega?",
      widgets: [
        {
          id: "serie",
          type: "timeseries",
          title: "Radicados en el tiempo",
          subtitle: "Por fecha de radicación",
          size: "full",
          compare: true,
          viz: "area",
          vizOptions: { mode: "auto" },
        },
        {
          id: "tipologia",
          type: "bar",
          orientation: "horizontal",
          title: "Tipología de PQRD",
          subtitle: "Participación de cada tipología",
          dimension: "tipologia_de_pqrd",
          size: "sm",
          viz: "composition",
          vizOptions: { layout: "legend" },
          maxItems: 5,
        },
        {
          id: "canales",
          type: "bar",
          orientation: "vertical",
          title: "Canal de radicación",
          subtitle: "Participación de cada canal de entrada",
          dimension: "canal_de_radicacion",
          // Mismo color por canal que en Entes de control (Email/Mail, Web, Ventanilla…)
          semantic: "canal-radicacion",
          size: "sm",
          viz: "composition",
          vizOptions: { layout: "legend" },
          maxItems: 5,
        },
      ],
      rows: [
        { template: "12", tier: "M", cells: ["serie"] },
        { template: "6-6", tier: "S", cells: ["tipologia", "canales"] },
      ],
    },
    {
      id: "oficinas",
      nav: "Oficinas",
      question: "¿Qué oficina responde?",
      widgets: [
        {
          id: "oficinas",
          type: "bar",
          orientation: "horizontal",
          title: "Oficinas responsables",
          subtitle: "Top 15 por radicados asignados",
          dimension: "oficina_responsable_de_respuesta",
          topN: 15,
          size: "md",
          viz: "ranking",
          vizOptions: { columns: 2, concentration: true },
          labelKind: "oficina",
          maxItems: 15,
        },
      ],
      rows: [{ template: "12", tier: "L", cells: ["oficinas"] }],
    },
    {
      id: "eficiencia",
      nav: "Eficiencia",
      question: "¿Qué gerencias son ágiles semana a semana?",
      description: "Días por fase frente a los cuartiles de 52 semanas: Q1 es lo más ágil y Q4 lo más lento.",
      widgets: [
        {
          id: "eficiencia",
          type: "efficiency",
          title: "Ranking de eficiencia por gerencia",
          subtitle: "Últimas 3 semanas por fase",
          size: "full",
          viz: "efficiency-matrix",
          labelKind: "oficina",
        },
      ],
      rows: [{ template: "12", tier: "auto", cells: ["eficiencia"] }],
    },
  ],
  table: {
    title: "Detalle de PQRD",
    // Mismo orden base que Entes (ENTES_TABLE_COLUMNS): identificación → estado y riesgo (badges a la vista) →
    // tiempo → clasificación → responsable. La fecha máxima casi nunca llega en la vista: oculta y al final.
    columns: [
      { field: "numero_de_radicado", label: "Radicado", format: "mono" },
      { field: "fecha_de_radicado", label: "Radicado el", format: "datetime" },
      { field: "estado", label: "Estado", format: "badge", semantic: "flujo" },
      { field: "semaforo_riesgo", label: "Semáforo", format: "badge", semantic: "semaforo" },
      { field: "tiempo_por_vencer", label: "Tiempo por vencer" },
      { field: "nombre_tipo_solicitud", label: "Tipo de solicitud" },
      { field: "tipologia_de_pqrd", label: "Tipología" },
      { field: "canal_de_radicacion", label: "Canal", semantic: "canal-radicacion" },
      { field: "oficina_responsable_de_respuesta", label: "Oficina responsable", labelKind: "oficina" },
      { field: "gestionador_responsable", label: "Gestionador", visible: false, labelKind: "persona" },
      { field: "fecha_maxima_de_respuesta", label: "Fecha máxima", format: "date", visible: false },
      { field: "rango_ciclo", label: "Rango ciclo", visible: false },
      { field: "observaciones", label: "Observaciones", format: "long", visible: false },
    ],
    searchFields: ["numero_de_radicado", "nombre_tipo_solicitud", "oficina_responsable_de_respuesta", "gestionador_responsable"],
    defaultSort: { field: "fecha_de_radicado", dir: "desc" },
  },
};
