import type { DashboardSpec } from "../types";
import { count, distinct, is, isNot, share, SEMAFORO_ORDER } from "./helpers";

export const smartMomento1: DashboardSpec = {
  slug: "smart-momento-1",
  dataset: "smart_m1",
  dateField: "fecha_registro_m1",
  dateLabel: "Fecha de registro (M1)",
  unit: { singular: "queja", plural: "quejas" },
  filters: [
    { field: "nombre_macro_motivo", label: "Macro motivo", kind: "multi", primary: true },
    { field: "nombre_producto", label: "Producto", kind: "multi", primary: true },
    { field: "nombre_canal", label: "Canal", kind: "multi", primary: true },
    { field: "nombre_tutela", label: "¿Tutela?", kind: "multi", primary: true },
    { field: "pqrd_estado", label: "Estado (PQRD)", kind: "multi" },
    { field: "nombre_condicion_especial", label: "Condición especial", kind: "multi" },
    { field: "pqrd_nombre_tipo_solicitud", label: "Tipo de solicitud (PQRD)", kind: "multi" },
    { field: "nombre_ente_control", label: "Ente de control", kind: "multi" },
    { field: "nombre_tipo_persona", label: "Tipo de persona", kind: "multi" },
    { field: "radicado", label: "Radicado", kind: "text" },
  ],
  kpis: [
    { id: "radicados", label: "Quejas registradas", short: "Quejas", measure: count(), format: "int", polarity: "neutral", hero: true, hint: "Quejas registradas en SMART (momento 1) en el periodo." },
    { id: "tutela", label: "% Con tutela", short: "% Con tutela", measure: share(is("nombre_tutela", "SÍ")), format: "pct", polarity: "up-bad", hint: "Quejas que reportan una acción de tutela asociada." },
    { id: "cruce", label: "% Cruzadas con PQRD", short: "% Cruce con PQRD", measure: share(isNot("pqrd_estado", "Sin cruce con PQRD")), format: "pct", polarity: "up-good", hint: "Quejas cuyo radicado se encontró en el seguimiento de PQRD (fuente de estado y semáforo)." },
    { id: "departamentos", label: "Departamentos", short: "Departamentos", measure: distinct("__dpto"), format: "int", polarity: "neutral", hint: "Departamentos distintos del consumidor financiero con al menos una queja." },
  ],
  // kpiRedesign §6: héroe + % Con tutela · % Cruce PQRD · Departamentos (3 × 112 + divisores = 360 ≤ 671)
  kpiLayout: [
    {
      template: "4-8",
      cells: [
        { kind: "hero", kpi: "radicados" },
        { kind: "group", title: "Riesgo y cobertura", variant: "list", kpis: ["tutela", "cruce", "departamentos"], gauges: ["cruce"] },
      ],
    },
  ],
  sections: [
    {
      id: "territorio",
      nav: "Territorio",
      question: "¿Desde dónde se quejan los consumidores?",
      widgets: [
        {
          id: "mapa",
          type: "map",
          title: "Ubicación del consumidor",
          subtitle: "Desglose por canal",
          geoLabel: "consumidor financiero",
          breakdown: { field: "nombre_canal", label: "Canal" },
          size: "full",
          viz: "hero-map",
          hero: true,
        },
      ],
      rows: [{ template: "12", tier: "XL", cells: ["mapa"] }],
    },
    {
      id: "tendencia",
      nav: "Tendencia",
      question: "¿Cómo evolucionan las quejas registradas?",
      widgets: [
        {
          id: "serie",
          type: "timeseries",
          title: "Quejas en el tiempo",
          subtitle: "Frente al periodo anterior",
          size: "full",
          compare: true,
          viz: "area",
          vizOptions: { mode: "auto", colorSlot: 1 },
        },
      ],
      rows: [{ template: "12", tier: "M", cells: ["serie"] }],
    },
    {
      id: "perfil",
      nav: "Perfil",
      question: "¿Qué producto, canal y género caracterizan las quejas?",
      widgets: [
        {
          id: "productos",
          type: "bar",
          orientation: "horizontal",
          title: "Productos",
          subtitle: "Quejas por producto de seguro",
          dimension: "nombre_producto",
          topN: 8,
          others: true,
          size: "full",
          viz: "ranking",
          vizOptions: { columns: 3 },
          maxItems: 9,
        },
        {
          id: "canales",
          type: "bar",
          orientation: "vertical",
          title: "Canales",
          subtitle: "Por dónde llega la queja",
          dimension: "nombre_canal",
          size: "md",
          viz: "composition",
          vizOptions: { layout: "legend" },
          maxItems: 6,
        },
        {
          id: "genero",
          type: "bar",
          orientation: "vertical",
          title: "Género",
          subtitle: "Del consumidor financiero",
          dimension: "nombre_sexo",
          size: "md",
          viz: "composition",
          vizOptions: { layout: "split" },
          maxItems: 4,
        },
      ],
      rows: [
        { template: "12", tier: "S", cells: ["productos"] },
        { template: "6-6", tier: "S", cells: ["canales", "genero"] },
      ],
    },
    {
      id: "calidad",
      nav: "Calidad del dato",
      question: "¿Qué tan completos llegan el motivo y el riesgo?",
      description: "Dos campos que la fuente casi nunca reporta: se muestran los registros con dato.",
      widgets: [
        {
          id: "macro-motivos",
          type: "bartable",
          title: "Macro motivos",
          subtitle: "Quejas por macro motivo",
          columns: [{ field: "nombre_macro_motivo", label: "Macro motivo" }],
          measureLabel: "Radicados",
          size: "md",
          viz: "quality-notice",
          vizOptions: { qualityVariant: "list", fallbackViz: "ranking" },
          maxItems: 14,
          note: "La fuente casi nunca reporta el macro motivo de la queja.",
        },
        {
          id: "semaforo",
          type: "bar",
          orientation: "vertical",
          title: "Semáforo de riesgo",
          subtitle: "Solo quejas cruzadas con PQRD",
          dimension: "pqrd_semaforo_riesgo",
          order: SEMAFORO_ORDER,
          size: "md",
          viz: "quality-notice",
          vizOptions: { qualityVariant: "status", fallbackViz: "status-strip" },
          semantic: "semaforo",
          maxItems: 3,
          note: "Solo las quejas cruzadas con PQRD tienen semáforo.",
        },
      ],
      rows: [{ template: "6-6", tier: "S", cells: ["macro-motivos", "semaforo"] }],
    },
  ],
  table: {
    title: "Detalle SMART · Momento 1",
    columns: [
      { field: "fecha_registro_m1", label: "Registro M1", format: "datetime" },
      { field: "radicado", label: "Radicado", format: "mono" },
      { field: "codigo_queja_reclamo", label: "Código queja/reclamo", format: "mono" },
      { field: "nombre_sexo", label: "Género" },
      { field: "nombre_tutela", label: "¿Tutela?" },
      { field: "nombre_producto", label: "Producto" },
      { field: "nombre_canal", label: "Canal" },
      { field: "nombre_macro_motivo", label: "Macro motivo" },
      { field: "nombre_departamento", label: "Departamento" },
      { field: "nombre_municipio", label: "Municipio" },
      { field: "nombre_condicion_especial", label: "Condición especial", visible: false },
      { field: "nombre_ente_control", label: "Ente de control", visible: false },
      { field: "nombre_tipo_persona", label: "Tipo de persona", visible: false },
      { field: "nombre_anexos_queja_reclamo", label: "Anexos", visible: false },
    ],
    searchFields: ["radicado", "codigo_queja_reclamo", "nombre_municipio"],
    defaultSort: { field: "fecha_registro_m1", dir: "desc" },
  },
};
