import type { DashboardSpec } from "../types";
import { count, is, share } from "./helpers";

export const smartMomento2: DashboardSpec = {
  slug: "smart-momento-2",
  dataset: "smart_m2",
  dateField: "fecha_registro_m2",
  dateLabel: "Fecha de registro (M2)",
  unit: { singular: "queja", plural: "quejas" },
  filters: [
    { field: "nombre_motivo", label: "Motivo", kind: "multi", primary: true },
    { field: "nombre_punto_recepcion", label: "Punto de recepción", kind: "multi", primary: true },
    { field: "nombre_tipo_persona", label: "Tipo de persona", kind: "multi", primary: true },
    { field: "nombre_anexos_queja_reclamo", label: "Anexos queja/reclamo", kind: "multi", primary: true },
    { field: "nombre_canal", label: "Canal", kind: "multi" },
    { field: "nombre_departamento", label: "Departamento", kind: "multi" },
    { field: "nombre_municipio", label: "Municipio", kind: "multi" },
    { field: "nombre_ente_control", label: "Ente de control", kind: "multi" },
    { field: "nombre_producto", label: "Producto", kind: "multi" },
    { field: "codigo_queja_reclamo", label: "Código queja/reclamo", kind: "text" },
  ],
  kpis: [
    { id: "total", label: "Quejas transmitidas", short: "Quejas", measure: count(), format: "int", polarity: "neutral", hero: true, hint: "Quejas registradas en el momento 2 (transmisión a la Superfinanciera)." },
    { id: "transmitido", label: "% Efectivamente transmitido", short: "% Transmitido", measure: share(is("caso_trasmitido_superfinanciera", "TRANSMITIDO")), format: "pct", polarity: "up-good", hint: "Casos con estado TRANSMITIDO sobre el total." },
    { id: "anexos", label: "% Con anexos", short: "% Con anexos", measure: share(is("nombre_anexos_queja_reclamo", "Sí")), format: "pct", polarity: "neutral", hint: "Quejas que incluyen anexos." },
    { id: "juridica", label: "% Persona jurídica", short: "% P. jurídica", measure: share(is("nombre_tipo_persona", "Jurídica")), format: "pct", polarity: "neutral", hint: "Quejas presentadas por personas jurídicas." },
  ],
  // kpiRedesign §6: héroe + % Transmitido · % Con anexos · % P. jurídica (3 × 112 + divisores = 360 ≤ 671)
  kpiLayout: [
    {
      template: "4-8",
      cells: [
        { kind: "hero", kpi: "total" },
        { kind: "group", title: "Transmisión y perfil", variant: "list", kpis: ["transmitido", "anexos", "juridica"], gauges: ["transmitido"] },
      ],
    },
  ],
  sections: [
    {
      id: "territorio",
      nav: "Territorio",
      question: "¿Desde dónde se quejan los consumidores?",
      widgets: [
        {
          id: "mapa",
          type: "map",
          title: "Ubicación del consumidor",
          subtitle: "Desglose por motivo",
          geoLabel: "consumidor financiero",
          breakdown: { field: "nombre_motivo", label: "Motivo" },
          size: "full",
          viz: "hero-map",
          hero: true,
        },
      ],
      rows: [{ template: "12", tier: "XL", cells: ["mapa"] }],
    },
    {
      id: "tendencia",
      nav: "Tendencia",
      question: "¿Cómo evolucionan las quejas transmitidas?",
      widgets: [
        {
          id: "serie",
          type: "timeseries",
          title: "Quejas en el tiempo",
          subtitle: "Frente al periodo anterior",
          size: "full",
          compare: true,
          viz: "area",
          vizOptions: { mode: "auto", colorSlot: 1 },
        },
      ],
      rows: [{ template: "12", tier: "M", cells: ["serie"] }],
    },
    {
      id: "motivos",
      nav: "Motivos",
      question: "¿Por qué se quejan los consumidores?",
      widgets: [
        {
          id: "motivos",
          type: "bar",
          orientation: "horizontal",
          title: "Motivos",
          subtitle: "Quejas por motivo con dato",
          dimension: "nombre_motivo",
          topN: 16,
          size: "full",
          viz: "treemap",
          vizOptions: { listToggle: true },
          maxItems: 16,
        },
      ],
      rows: [{ template: "12", tier: "L", cells: ["motivos"] }],
    },
    {
      id: "recepcion",
      nav: "Recepción",
      question: "¿Cómo llega la queja?",
      widgets: [
        {
          id: "producto",
          type: "bar",
          orientation: "horizontal",
          title: "Producto",
          subtitle: "Producto de seguro reclamado",
          dimension: "nombre_producto",
          size: "md",
          viz: "composition",
          vizOptions: { layout: "legend" },
          maxItems: 8,
        },
        {
          id: "punto",
          type: "bar",
          orientation: "vertical",
          title: "Punto de recepción",
          subtitle: "Dónde se recibió la queja",
          dimension: "nombre_punto_recepcion",
          size: "md",
          viz: "composition",
          vizOptions: { layout: "legend" },
          maxItems: 4,
        },
        {
          id: "persona",
          type: "bar",
          orientation: "vertical",
          title: "Tipo de persona",
          subtitle: "Natural o jurídica",
          dimension: "nombre_tipo_persona",
          size: "md",
          viz: "composition",
          vizOptions: { layout: "split" },
          maxItems: 2,
        },
        {
          id: "canal",
          type: "bar",
          orientation: "vertical",
          title: "Canal",
          // A span 4 (≈ 244 px internos a 1024) el subtítulo de una línea no puede repetir "Canal"
          subtitle: "Reportado a la Superfinanciera",
          dimension: "nombre_canal",
          size: "md",
          viz: "composition",
          vizOptions: { layout: "legend" },
          maxItems: 5,
        },
      ],
      // Las dos filas en 8-4: los bordes de las tarjetas quedan alineados en la misma rejilla (un 6-6 debajo
      // del 8-4 los escalonaba). Canal (aviso de calidad: titular + barra + 2 filas ≈ 150 ≤ 184) cabe en 4 y
      // Punto, en 8, reparte su leyenda en 2 columnas (24 + 2 × 24 = 72 ≤ 184).
      rows: [
        { template: "8-4", tier: "S", cells: ["producto", "persona"] },
        { template: "8-4", tier: "S", cells: ["punto", "canal"] },
      ],
    },
  ],
  table: {
    title: "Detalle SMART · Momento 2",
    columns: [
      { field: "fecha_registro_m2", label: "Registro M2", format: "datetime" },
      { field: "codigo_queja_reclamo", label: "Código queja/reclamo", format: "mono" },
      { field: "nombre_motivo", label: "Motivo" },
      { field: "nombre_canal", label: "Canal" },
      { field: "nombre_departamento", label: "Departamento" },
      { field: "nombre_municipio", label: "Municipio" },
      { field: "nombre_producto", label: "Producto" },
      { field: "caso_trasmitido_superfinanciera", label: "Transmitido", format: "badge", semantic: "transmision" },
      { field: "nombre_punto_recepcion", label: "Punto de recepción" },
    ],
    searchFields: ["codigo_queja_reclamo", "nombre_motivo", "nombre_municipio"],
    defaultSort: { field: "fecha_registro_m2", dir: "desc" },
  },
};
