import type { DashboardSpec } from "../types";
import { count, is, share } from "./helpers";

/** Etapas del proceso judicial en orden (Duplicado sale del flujo; No reporta va en nota). */
const ETAPAS_ORDER = ["Avoco", "Oficios", "Fallo de primera instancia", "Fallo de segunda instancia", "Desacato", "Duplicado", "No reporta"];

/** Familias del estado del fallo (familia semántica "fallo"; por validar con jurídica). Los 15 estados reales. */
const FALLO_FAMILIES = [
  { label: "Favorable", tone: "good" as const, members: ["A favor", "Confirma a Favor", "Revoca a Favor", "Revoca Sanción"] },
  { label: "Desfavorable", tone: "critical" as const, members: ["En Contra", "Confirma en Contra", "Revoca en Contra", "Sanción"] },
  {
    // "Trámite" (corto): "Trámite o informativo" partía en 2 líneas y descuadraba la cabecera del FamilySplit
    label: "Trámite",
    // Categoría real (no dato faltante): info, para que "Sin dato" sea el único gris
    tone: "info" as const,
    // "Informativos" es alias documentado de "Informativo" (la fuente usa ambos).
    members: ["Informativo", "Informativos", "Cierre", "Requerimiento Previo", "Segundo Requerimiento", "Oficios de Trámite", "Decreta Nulidad"],
  },
];

export const tutelas: DashboardSpec = {
  slug: "tutelas",
  dataset: "tutelas",
  dateField: "fecharadicacion",
  dateLabel: "Fecha de radicación",
  unit: { singular: "tutela", plural: "tutelas" },
  filters: [
    { field: "Etapa_procesal", label: "Etapa procesal", kind: "multi", primary: true },
    { field: "Cerrado", label: "Estado de cumplimiento", kind: "multi", primary: true },
    { field: "Dependencia", label: "Dependencia", kind: "multi", primary: true },
    { field: "canal", label: "Canal", kind: "multi", primary: true },
    { field: "Gestionador", label: "Gestionador", kind: "multi" },
    { field: "Causal", label: "Causal", kind: "multi" },
    { field: "Estado_del_fallo", label: "Estado del fallo", kind: "multi" },
    { field: "estado", label: "Estado", kind: "multi" },
    { field: "Tiempo_para_responder", label: "Tiempo para responder", kind: "multi" },
    { field: "Radicado", label: "Radicado", kind: "text" },
    { field: "Numero_de_radicado_juzgado", label: "N° radicado juzgado", kind: "text" },
  ],
  kpis: [
    { id: "tutelas", label: "Tutelas", short: "Tutelas", measure: count(), format: "int", polarity: "neutral", hero: true, hint: "Tutelas radicadas en el periodo." },
    { id: "en-termino", label: "% En término", short: "En término", measure: share(is("Cerrado", "En término")), format: "pct", polarity: "up-good", hint: "Respuesta enviada antes de la fecha de respuesta del juzgado." },
    { id: "fuera-termino", label: "% Fuera de término", short: "Fuera de término", measure: share(is("Cerrado", "Fuera de término")), format: "pct", polarity: "up-bad", hint: "Respuesta enviada después de la fecha de respuesta del juzgado." },
    { id: "en-tramite", label: "En trámite", short: "En trámite", measure: count(is("Cerrado", "En trámite")), format: "int", polarity: "neutral", hint: "Tutelas sin respuesta enviada todavía." },
    { id: "pct-tramite", label: "% En trámite", short: "En trámite", measure: share(is("Cerrado", "En trámite")), format: "pct", polarity: "neutral", hint: "Tutelas en trámite sobre el total." },
    {
      id: "desacato",
      label: "Tasa de desacato",
      short: "Desacato",
      measure: { kind: "ratioOf", num: count(is("Etapa_procesal", "Desacato")), den: count(is("Etapa_procesal", "Fallo de primera instancia")) },
      format: "pct",
      polarity: "up-bad",
      provisional: true,
      hint: "Tutelas en etapa Desacato sobre tutelas con fallo de primera instancia. Fórmula provisional: validar con el área jurídica.",
    },
  ],
  // kpiRedesign §6: 3-6-3 · [héroe tutelas] [proporción "Cumplimiento de términos" + en trámite como secundaria] [tile desacato provisional]
  kpiLayout: [
    {
      template: "3-6-3",
      cells: [
        { kind: "hero", kpi: "tutelas" },
        {
          kind: "group",
          title: "Cumplimiento de términos",
          variant: "proportion",
          kpis: ["en-termino", "fuera-termino", "pct-tramite"],
          tones: ["good", "serious", "info"],
          filters: [
            { field: "Cerrado", value: "En término" },
            { field: "Cerrado", value: "Fuera de término" },
            { field: "Cerrado", value: "En trámite" },
          ],
          secondary: "en-tramite",
        },
        {
          kind: "tile",
          kpi: "desacato",
          variant: "status",
          tone: "critical",
          action: { label: "Ver desacatos", filter: { field: "Etapa_procesal", value: "Desacato" } },
        },
      ],
    },
  ],
  sections: [
    {
      id: "etapa",
      nav: "Etapa y estado",
      question: "¿En qué punto del proceso están las tutelas?",
      widgets: [
        {
          id: "etapas",
          type: "bar",
          orientation: "horizontal",
          title: "Etapa procesal",
          subtitle: "Tutelas por etapa del proceso judicial",
          dimension: "Etapa_procesal",
          sort: "natural",
          order: ETAPAS_ORDER,
          size: "full",
          viz: "pipeline",
          // Etiquetas cortas en los chevrons (alias de presentación: el filtro cruzado usa el valor original)
          vizOptions: {
            criticalStages: ["Desacato"],
            exits: ["Duplicado"],
            overrides: { "Fallo de primera instancia": { label: "Fallo 1.ª instancia" }, "Fallo de segunda instancia": { label: "Fallo 2.ª instancia" } },
          },
          // Pasos del flujo (Avoco → Desacato); Duplicado va como chip y No reporta como nota.
          maxItems: 5,
        },
        {
          id: "estado",
          type: "bar",
          orientation: "vertical",
          title: "Estado del radicado",
          subtitle: "Ciclo de vida de la respuesta",
          dimension: "estado",
          size: "sm",
          viz: "composition",
          vizOptions: { layout: "legend" },
          semantic: "flujo",
          maxItems: 5,
        },
        {
          id: "canal",
          type: "bar",
          orientation: "vertical",
          title: "Canal de radicado",
          subtitle: "Por dónde llegan las tutelas",
          dimension: "canal",
          // Mismo color por canal que en PQRD, Entes y ML entradas (Mail naranja, Ventanilla aqua, Mail IA
          // amarillo): sin familia, Mail IA tomaba el azul que en PQRD significa Web.
          semantic: "canal-radicacion",
          size: "sm",
          viz: "composition",
          vizOptions: { layout: "split" },
          maxItems: 3,
        },
        {
          id: "dependencia",
          type: "bar",
          orientation: "horizontal",
          title: "Dependencia",
          subtitle: "Gerencia a cargo de la respuesta",
          dimension: "Dependencia",
          size: "sm",
          viz: "composition",
          vizOptions: { layout: "split", overrides: { "GERENCIA DE INDEMNIZACIONES, GERENCIA MÉDICA": { label: "Ambas gerencias" } } },
          labelKind: "oficina",
          maxItems: 4,
        },
      ],
      rows: [
        { template: "12", tier: "S", cells: ["etapas"] },
        { template: "4-4-4", tier: "S", cells: ["estado", "canal", "dependencia"] },
      ],
    },
    {
      id: "territorio",
      nav: "Territorio",
      question: "¿Desde dónde llegan las tutelas?",
      widgets: [
        {
          id: "mapa",
          type: "map",
          title: "Territorio de la tutela",
          subtitle: "Departamento y municipio · por etapa",
          geoLabel: "tutela",
          breakdown: { field: "Etapa_procesal", label: "Etapa procesal" },
          size: "full",
          viz: "hero-map",
          hero: true,
        },
      ],
      rows: [{ template: "12", tier: "XL", cells: ["mapa"] }],
    },
    {
      id: "tendencia",
      nav: "Tendencia",
      question: "¿Cómo evoluciona la radicación de tutelas?",
      widgets: [
        {
          id: "serie",
          type: "timeseries",
          title: "Tutelas radicadas",
          subtitle: "Frente al periodo anterior",
          size: "full",
          compare: true,
          viz: "area",
          vizOptions: { mode: "auto" },
        },
      ],
      rows: [{ template: "12", tier: "M", cells: ["serie"] }],
    },
    {
      id: "fallos",
      nav: "Fallos y causales",
      question: "¿Cómo se falla, por qué y desde dónde nos demandan?",
      widgets: [
        {
          id: "causales",
          type: "bar",
          orientation: "horizontal",
          title: "Causales",
          subtitle: "Principales motivos de la tutela",
          dimension: "Causal",
          topN: 10,
          size: "full",
          viz: "ranking",
          vizOptions: { columns: 2, twoLine: true, concentration: true },
          maxItems: 10,
        },
        {
          id: "fallos",
          type: "bar",
          orientation: "horizontal",
          title: "Estado del fallo",
          subtitle: "Estados agrupados por sentido del fallo",
          dimension: "Estado_del_fallo",
          size: "md",
          viz: "family-split",
          vizOptions: { families: FALLO_FAMILIES },
          semantic: "fallo",
          maxItems: 15,
          note: "Agrupación por sentido del fallo pendiente de validar con el área jurídica.",
        },
        {
          id: "departamentos",
          type: "bar",
          orientation: "horizontal",
          title: "Juzgado remitente · departamento",
          subtitle: "Geografía del juzgado, distinta al mapa",
          dimension: "Departamento_remitente",
          topN: 10,
          size: "md",
          viz: "ranking",
          vizOptions: { columns: 2, compact: true },
          maxItems: 10,
        },
      ],
      rows: [
        { template: "12", tier: "L", cells: ["causales"] },
        { template: "6-6", tier: "M", cells: ["fallos", "departamentos"] },
      ],
    },
    {
      id: "responsables",
      nav: "Responsables",
      question: "¿Quién gestiona las tutelas?",
      widgets: [
        {
          id: "gestionadores",
          type: "bar",
          orientation: "horizontal",
          title: "Gestionadores",
          subtitle: "Tutelas asignadas",
          dimension: "Gestionador",
          topN: 20,
          size: "full",
          viz: "people",
          // Compacta como en ML: 7 × 34 = 238 + pie 28 = 266 ≤ 284 (M), sin aire al pie
          vizOptions: { columns: 3, compact: true },
          labelKind: "persona",
          maxItems: 20,
        },
      ],
      rows: [{ template: "12", tier: "M", cells: ["gestionadores"] }],
    },
  ],
  table: {
    title: "Detalle de tutelas",
    columns: [
      { field: "Radicado", label: "Radicado", format: "mono" },
      { field: "fecharadicacion", label: "Radicada el", format: "datetime" },
      { field: "dias_transcurridos", label: "Días transcurridos", format: "int" },
      { field: "Tiempo_para_responder", label: "Tiempo para responder" },
      { field: "Cerrado", label: "Estado de cumplimiento", format: "badge", semantic: "cumplimiento" },
      { field: "Etapa_procesal", label: "Etapa procesal" },
      { field: "Estado_del_fallo", label: "Estado del fallo", semantic: "fallo" },
      { field: "Departamento_remitente", label: "Departamento", visible: false },
      { field: "Dependencia", label: "Dependencia", labelKind: "oficina" },
      { field: "Gestionador", label: "Gestionador", labelKind: "persona" },
      { field: "Causal", label: "Causal", format: "long", visible: false },
      { field: "Numero_de_radicado_juzgado", label: "N° radicado juzgado", format: "mono", visible: false },
      { field: "canal", label: "Canal", visible: false, semantic: "canal-radicacion" },
    ],
    searchFields: ["Radicado", "Numero_de_radicado_juzgado", "Gestionador", "Causal"],
    defaultSort: { field: "fecharadicacion", dir: "desc" },
  },
};
